apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub-rabbitmq
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: connectionString
      value: "amqp://admin:admin123@rabbitmq:5672"
    - name: durable
      value: "true"
    - name: enableDeadLetter
      value: "true"